language: node_js
node_js:
  - '6'
before_deploy:
  - ./scripts/script.sh && cd dir1
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/gh-pages
    email: 'embbnux@embbnux.com'
    name: 'Embbnux Ji'
    on:
      branch: master
      node: '6'
      tags: true
