language: node_js
node_js:
  - '6'
before_deploy:
  - ./scripts/script.sh && cd dir1
deploy:
  - provider: script
    script: dir1/script1.sh
    skip_cleanup: true
    on:
      node: '6'
      tags: true
  # - provider: script
  #   script: dir2/script2.sh
  #   on:
  #     node: '6'
  #     tags: true
